/**
 * Phase 1 / method B — seed on the device itself.
 *
 * This exists to answer "what is the worst case a user would sit through if the
 * app had to build the dataset itself?", not because it is a good idea. Method A
 * (offline build + adb push, see scripts/seed.ts) is the default.
 *
 * The row data is generated by the same src/db/rowgen.ts the Node script uses,
 * so a method-B database holds the same values as a method-A one — only the
 * physical page layout differs (different insert-time pragmas, no ANALYZE
 * before the index is built).
 */

import { open, type DB, type Scalar } from '@op-engineering/op-sqlite';

import { DB_LOCATION } from './device';
import { makeRng, makeRow } from './rowgen';
import {
  CREATE_TABLE_SQL,
  INDEX_SQL,
  INSERT_SQL,
  qrCodeForId,
  type IndexMode,
} from './schema';

export interface SeedOptions {
  fileName: string;
  rows: number;
  /** Rows per transaction. 10k is the sweet spot on the emulator. */
  batch?: number;
  index?: IndexMode;
  seed?: number;
  /** Called after each batch so the UI can show progress. */
  onProgress?: (done: number, total: number, elapsedMs: number) => void;
}

export interface SeedReport {
  fileName: string;
  rows: number;
  batch: number;
  index: IndexMode;
  insertMs: number;
  indexMs: number;
  analyzeMs: number;
  totalMs: number;
  rowsPerSecond: number;
  countVerified: number;
}

/**
 * Insert-time pragmas, mirroring scripts/seed.ts. These make the *build* fast
 * and are irrelevant to lookup speed — the benchmark re-applies its own runtime
 * pragmas when it opens the file.
 */
const BULK_PRAGMAS = [
  'PRAGMA journal_mode = OFF;',
  'PRAGMA synchronous = OFF;',
  'PRAGMA cache_size = -200000;',
  'PRAGMA temp_store = MEMORY;',
];

/**
 * `executeBatch` is the important part: it ships one array across the JSI
 * boundary and loops in C++ inside a single transaction. Inserting row-by-row
 * from JS is roughly an order of magnitude slower and is what the prompt's
 * "do not do this" refers to.
 */
export const seedInApp = async (opts: SeedOptions): Promise<SeedReport> => {
  const {
    fileName,
    rows,
    batch = 10_000,
    index = 'unique',
    seed = 42,
    onProgress,
  } = opts;

  const db: DB = open({ name: fileName, location: DB_LOCATION });

  try {
    db.executeSync('DROP TABLE IF EXISTS items;');
    db.executeSync(CREATE_TABLE_SQL);
    for (const p of BULK_PRAGMAS) db.executeSync(p);

    const rng = makeRng(seed);
    const tInsert = performance.now();

    for (let from = 1; from <= rows; from += batch) {
      const to = Math.min(from + batch - 1, rows);
      const params: Scalar[][] = new Array(to - from + 1);
      for (let id = from; id <= to; id += 1) {
        params[id - from] = makeRow(rng, id, qrCodeForId(id));
      }
      // One tuple, many parameter sets → one native transaction.
      await db.executeBatch([[INSERT_SQL, params]]);
      onProgress?.(to, rows, performance.now() - tInsert);
    }

    const insertMs = performance.now() - tInsert;

    const indexSql = INDEX_SQL[index];
    const tIndex = performance.now();
    if (indexSql) await db.execute(indexSql);
    const indexMs = performance.now() - tIndex;

    const tAnalyze = performance.now();
    await db.execute('ANALYZE;');
    const analyzeMs = performance.now() - tAnalyze;

    const countRes = db.executeSync('SELECT COUNT(*) AS n FROM items;');
    const countVerified = Number(countRes.rows[0]?.n ?? 0);
    if (countVerified !== rows) {
      throw new Error(`row count mismatch: expected ${rows}, got ${countVerified}`);
    }

    return {
      fileName,
      rows,
      batch,
      index,
      insertMs,
      indexMs,
      analyzeMs,
      totalMs: insertMs + indexMs + analyzeMs,
      rowsPerSecond: Math.round(rows / (insertMs / 1000)),
      countVerified,
    };
  } finally {
    db.close();
  }
};
